### ISSUE TITLE
Remove "Log In" text from each page when user isn't logged in.

### ISSUE THREAD

**Issue by heinsdorf** [leftforum/mainsite#13]
On those two pages the text “Log in” shows up on each page. We do not need that. Also the Line underneath that “Log in” text can go. 

See image:
https://docs.google.com/document/d/1C-IXwKLG7NAHJTscR247Qs-BGXJAwu8VXwxGFDL63po/edit?usp=sharing

**Comment by andriijang** [comment]
Done
